### ISSUE TITLE
Icons not found with vim.g.netrw_liststyle = 3

### ISSUE THREAD

**Issue by CRAG666** [prichrd/netrw.nvim#16]
As the ISSUE says, I try to configure the tree view and the icons are disable:
![image](https://user-images.githubusercontent.com/34254373/204934699-a9a4dbeb-fb79-455c-b83a-44c54709207c.png)

**Comment by CRAG666** [comment]
thanks

**Comment by omaru-ok** [comment]
@prichrd quick question , how can i have all possible keybinds which can be modified?!
and what how to i set keybinds for 
`UP/Change parent dir/cd ..`

**Comment by prichrd** [comment]
Hey @omaru-ok, would you mind creating a separate issue? I will try to assist you on how to create such a binding. The plugin doesn't have pre-configured action at the moment, so we'll have to create a custom mapping.

**Comment by omaru-ok** [comment]
@prichrd i think maknin netrw great is very BASED CHAD  move , 
but i have offcial switched to [sfm](https://github.com/dinhhuy258/sfm.nvim) , its a kinda of plugin i was looking , SIMPLE yet extensive

**Comment by omaru-ok** [comment]
for now it would be better to have everything nicely documented, in readme, or wiki

**Comment by kitsugo** [comment]
Has any working prototype of this been completed yet? I like using netrw as a very minimal file viewer, yet I prefer a tree view the most as it closely resembles the view of most other "fully-featured" file-explorer plugins. I'd be happy to see progress on this or potentially help with any development effort.

**Comment by prichrd** [comment]
Hey @kitsugo!

List style three is almost done; it just needs a bit more testing (see [more-list-styles](https://github.com/prichrd/netrw.nvim/tree/more-list-styles)). If you are interested in getting this through the line, I'd be happy to help you get it through the door. If not, I should be able to get this out in the upcoming days.

Here's a little sneak peek of what the code of [more-list-styles](https://github.com/prichrd/netrw.nvim/tree/more-list-styles) contains:
<img width="732" alt="image" src="https://github.com/prichrd/netrw.nvim/assets/3706527/eb2abf2f-8ffa-41f0-be3a-dd057baad3ce">
