### ISSUE TITLE
create file without opening

### ISSUE THREAD

**Issue by backwardspy** [prichrd/netrw.nvim#19]
hi, love this plugin!

sometimes i want to create several files in a row without immediately opening any of them. i don't think vanilla netrw supports this, so it seems a custom mapping might be the way to go.

i'd really appreciate some guidance on how to achieve this!

**Comment by prichrd** [comment]
Hey @backwardspy,

I appreciate your interest in the plugin. It is indeed possible to do this with custom mappings. Here is an example of what you could do:

```lua
require 'netrw'.setup {
        mappings = {
          ["n"] = function(_)
            local action_create = function(fname)
              -- Netrw sets a buffer variable for the current dir. We can
              -- concatenate that path with the provided file name.
              local new_fpath = vim.b.netrw_curdir .. '/' .. fname

              -- We create the file using vim.loop. For more info, see `:h uv`
              local ok, fd = pcall(vim.loop.fs_open, new_fpath, "w", 420)
              if not ok then
                vim.notify("error creating file", vim.log.levels.ERROR)
                return
              end
              vim.loop.fs_close(fd)

              -- Netrw binds <C-l> (refresh) to the following function call.
              vim.cmd [[call <SNR>33_NetrwRefresh(1,<SNR>33_NetrwBrowseChgDir(1,(exists("w:netrw_liststyle") && exists("w:netrw_treetop") && w:netrw_liststyle == 3)? w:netrw_treetop : './'))]]
            end

            -- Create a prompt (see `:h vim.ui.input` for more options)
            vim.ui.input({ prompt = 'Enter filename: ' }, action_create)
          end,
        },
      }
```

It doesn't have all the bells and whistles, but it is a good starting point. I might add to this plugin a set of bindable actions like this one. I never thought of your specific use case and I think a lot of people could benefit from it.

Let me know if that helps!

**Comment by backwardspy** [comment]
that is perfect, thank you for the help! i like the idea of a cookbook of sorts for functions like this. could be quite useful. :)
