### ISSUE TITLE
Icons dont show when sign columns are set to no

### ISSUE THREAD

**Issue by shesmu** [prichrd/netrw.nvim#26]
Not sure if this is really considered an issue because Im guessing that sign columns are the core of how this plugin works but if its not or there is an easy workaround this is an issue to note

**Comment by prichrd** [comment]
Hey @shesmu!

Unfortunately, the plugin relies on the sign column feature and cannot work without it. If you globally disable the sign column but only want to activate it for netrw, you could do the following: 

``` viml
augroup NetrwSignColumn
  autocmd!
  au FileType netrw setlocal signcolumn=yes
augroup end
```

**Comment by shesmu** [comment]
Hey @prichrd 

Thanks for the very helpful response, wrapped it in a lua `autocmd` but the command works a treat, why not just make make it part of the plugin?

**Comment by prichrd** [comment]
Hey @shesmu,

I totally agree with you, I have embedded it into the plugin. You should be able to update the plugin and remove the autocmd from your Neovim config :)

Thank you for raising the issue!
